apiVersion: v1
kind: Service
metadata:
  name: codesage-frontend
  namespace: codesage
  labels:
    app: codesage-frontend
spec:
  type: ClusterIP
  selector:
    app: codesage-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
