sonar.organization=Wael-BenHariz
sonar.projectKey=Wael-BenHariz_CODESAGE

sonar.projectName=CODESAGE
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/coverage/**,\
**/htmlcov/**,\
**/*.min.js,\
**/migrations/**

sonar.tests=backend/tests

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
