apiVersion: v1
kind: Service
metadata:
  name: semgrep-service
  namespace: codesage
  labels:
    app: semgrep-service
spec:
  type: ClusterIP
  selector:
    app: semgrep-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
