apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: codesage
type: Opaque
stringData:
  POSTGRES_DB: codesage
  POSTGRES_USER: codesage
  POSTGRES_PASSWORD: codesage
  DATABASE_URL: postgresql+asyncpg://codesage:codesage@postgres-service.codesage.svc.cluster.local:5432/codesage
