apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: codesage
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    requirepass redis_password
